apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shorty

generatorOptions:
  disableNameSuffixHash: true

resources:
  - namespace.yaml
  - stack.yaml

configMapGenerator:
  - name: prometheus-config
    files:
      - config/prometheus.yml
  - name: loki-config
    files:
      - config/loki-config.yaml
  - name: grafana-datasources
    files:
      - config/datasources.yaml
  - name: grafana-dashboards-provider
    files:
      - config/dashboards.yml
  - name: grafana-dashboards
    files:
      - config/postgres-overview.json
