global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [ "prometheus:9090" ]

  - job_name: analytics-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'analytics-service:8091' ]

  - job_name: url-shortener-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'url-shortener-service:8092' ]

  - job_name: grafana
    metrics_path: /metrics
    static_configs:
      - targets: [ 'grafana:3000' ]

  - job_name: alloy
    metrics_path: /metrics
    static_configs:
      - targets: [ 'alloy:9080' ]

  - job_name: loki
    metrics_path: /metrics
    static_configs:
      - targets: [ 'loki:3100' ]

  - job_name: url-shortener-postgres
    static_configs:
      - targets: [ 'url-shortener-postgres-exporter:9187' ]

# todo: add analytics-service-postgres